export type Lang = 'en' | 'ar';

export const translations = {
  en: {
    welcome: "Welcome Back",
    ready: "Ready to shadow your way to fluency?",
    streak: "Current Practice Streak",
    longest: "Longest Streak",
    day: "Day",
    days: "Days",
    totalShadowings: "Total Shadowings",
    avgScore: "Avg Accuracy Score",
    weeklyProgress: "Weekly Progress",
    attemptsPerDay: "Attempts / Day",
    focusTip: "Focus Tip for Today",
    tipBody: "Listen closely to vowel coloring in General American English. Pay attention to rhoticity (the American \"r\") in words like \"water\" or \"there.\" Practice mimicking the exact pitch contour of the prompt!",
    startPractice: "Start Daily Practice",
    progress: "Progress",
    sentenceOf: "Sentence {x} of {y}",
    playingPrompt: "Playing prompt accent...",
    listen: "Listen",
    record: "Record",
    stop: "Stop",
    analyzing: "Analyzing speech acoustics...",
    feedbackPraise: "Praise",
    feedbackCorrection: "Corrective Advice",
    accuracyScore: "Acoustic Score",
    accentAlignment: "General American accent alignment",
    nextSentence: "Next Sentence",
    finishSession: "Finish Session",
    sessionComplete: "Session Complete!",
    sessionDesc: "You just mastered another shadowing round.",
    avgScoreLabel: "Avg Score",
    time: "Time",
    sessionLog: "Session Log",
    home: "Home",
    restart: "Restart",
    voiceSpeed: "Voice Speed",
    tipTitle: "Focus Tip for Today",
    nativeGrade: "Native-grade fluency",
    nativeGradeDesc: "Incredible job! Your articulation and rhythm closely mimic native General American English parameters.",
    clearArtic: "Clear articulation",
    clearArticDesc: "Great work! You have clean phrasing. Keep polishing minor vowel coloring and consonant clarity.",
    keepPractice: "Keep practicing rhythm mechanics",
    keepPracticeDesc: "Keep at it! Pay attention to rhoticity (the American \"r\") and smooth syllable pacing to improve.",
    errorTitle: "Evaluation Error",
    preparing: "Preparing practice block...",
    analyzingAcoustics: "Analyzing speech acoustics...",
    micDenied: "Microphone access denied. Please verify browser permissions.",
    praiseLabel: "Praise",
    correctionLabel: "Correction",
    goBack: "Go back",
    shadowingPractice: "Shadowing Practice",
    acousticScore: "Acoustic Score",
    accentAlignDetail: "General American accent alignment",
    networkError: "Connection error. Please check your internet connection.",
    apiError: "API evaluation failed. Please verify API key configuration.",
    invalidResponse: "Received an invalid grading response. Please try again.",
    unknownError: "An unknown error occurred. Please try again.",
    // V2 Setup Translations
    practiceSetup: "Practice Setup",
    selectCategory: "Select Practice Category",
    selectDifficulty: "Select Practice Level",
    startPracticeBtn: "Start Session",
    noSentencesFound: "No sentences found matching your criteria. Try another filter.",
    cat_daily: "Daily Conversation",
    cat_business: "Business",
    cat_travel: "Travel",
    cat_news: "News",
    cat_movies: "Movies",
    diff_beginner: "Beginner",
    diff_intermediate: "Intermediate",
    diff_advanced: "Advanced",
    // Weakness Tracking Translations (V2 Task 9)
    weaknessesTitle: "Acoustic Weaknesses",
    weaknessesDesc: "Your most common pronunciation mistakes across all sessions:",
    timesMispronounced: "{count} times",
    // V2 Source Mode Translations (Task 4)
    selectSourceMode: "Practice Phrasing Source",
    modeStatic: "Standard Bank",
    modeAI: "AI Personalized Generator",
    generatingAI: "Generating AI practice sentences...",
    // V2 Paragraph & Achievement Translations
    selectSessionMode: "Select Practice Mode",
    modeSentence: "Sentence Mode",
    modeParagraph: "Paragraph Mode",
    sessionModeSentenceDesc: "Practice with short, individual sentences (10 rounds)",
    sessionModeParagraphDesc: "Practice with multi-sentence paragraphs (5 rounds)",
    practiceMode: "Practice Mode",
    achievementsTitle: "Unlocked Achievements",
    achievementsDesc: "Your milestones unlocked during practice:",
    downloadCard: "Download Share Card",
    generatingShareCard: "Generating share card...",
    achievementsUnlockedNotify: "New Achievement Unlocked!"
  },
  ar: {
    welcome: "مرحباً بك مجدداً",
    ready: "هل أنت مستعد للممارسة والوصول إلى الطلاقة؟",
    streak: "سلسلة الممارسة الحالية",
    longest: "أطول سلسلة ممارسة",
    day: "يوم",
    days: "أيام",
    totalShadowings: "إجمالي المحاولات",
    avgScore: "متوسط نسبة الدقة",
    weeklyProgress: "التقدم الأسبوعي",
    attemptsPerDay: "المحاولات / اليوم",
    focusTip: "نصيحة اليوم للتركيز",
    tipBody: "استمع جيداً لنطق الحروف المتحركة في اللهجة الأمريكية العامة. انتبه لنطق حرف الـ \"r\" في كلمات مثل \"water\" أو \"there\". تدرب على محاكاة نبرة الصوت الدقيقة للجملة!",
    startPractice: "ابدأ الممارسة اليومية",
    progress: "التقدم",
    sentenceOf: "الجملة {x} من {y}",
    playingPrompt: "جاري تشغيل نطق الجملة...",
    listen: "استمع",
    record: "سجل",
    stop: "إيقاف",
    analyzing: "جاري تحليل نبرة الصوت...",
    feedbackPraise: "الإشادة",
    feedbackCorrection: "نصيحة للتصحيح",
    accuracyScore: "درجة النطق",
    accentAlignment: "التوافق مع اللهجة الأمريكية العامة",
    nextSentence: "الجملة التالية",
    finishSession: "إنهاء الجلسة",
    sessionComplete: "اكتملت الجلسة!",
    sessionDesc: "لقد أتقنت جولة أخرى من التدريب.",
    avgScoreLabel: "متوسط الدرجة",
    time: "الوقت",
    sessionLog: "سجل الجلسة",
    home: "الرئيسية",
    restart: "إعادة البدء",
    voiceSpeed: "سرعة الصوت",
    tipTitle: "نصيحة اليوم للتركيز",
    nativeGrade: "طلاقة بمستوى المتحدث الأصلي",
    nativeGradeDesc: "عمل رائع! نطقك ومخارج الحروف لديك قريبة جداً من اللهجة الأمريكية العامة.",
    clearArtic: "نطق واضح ومفهوم",
    clearArticDesc: "عمل جيد! نطقك واضح. استمر في التدرب لتحسين نطق الحروف المتحركة البسيطة ومخارج الحروف.",
    keepPractice: "استمر في التدرب على الإيقاع",
    keepPracticeDesc: "واصل التدريب! ركز على نطق حرف الـ \"r\" الأمريكي وتدفق الجملة بشكل أكثر سلاسة.",
    errorTitle: "خطأ في التقييم",
    preparing: "جاري تجهيز جمل الممارسة...",
    analyzingAcoustics: "جاري تحليل الخصائص الصوتية للخطاب...",
    micDenied: "تم رفض الوصول للميكروفون. يرجى تفعيل الصلاحيات من إعدادات المتصفح.",
    praiseLabel: "الإشادة",
    correctionLabel: "التصحيح",
    goBack: "رجوع",
    shadowingPractice: "التدريب على المحاكاة",
    acousticScore: "درجة النطق",
    accentAlignDetail: "التوافق مع اللهجة الأمريكية العامة",
    networkError: "خطأ في الاتصال. يرجى التحقق من اتصالك بالإنترنت.",
    apiError: "فشل تقييم واجهة برمجة التطبيقات. يرجى التحقق من إعداد مفتاح API الخاص بك.",
    invalidResponse: "تم استلام استجابة غير صالحة من نظام التقييم. يرجى إعادة المحاولة.",
    unknownError: "حدث خطأ غير معروف. يرجى المحاولة مرة أخرى.",
    // V2 Setup Translations
    practiceSetup: "إعداد التدريب",
    selectCategory: "اختر تصنيف التدريب",
    selectDifficulty: "اختر مستوى التدريب",
    startPracticeBtn: "بدء الجلسة",
    noSentencesFound: "لم يتم العثور على جمل تطابق اختياراتك. جرب فلترة أخرى.",
    cat_daily: "محادثات يومية",
    cat_business: "الأعمال",
    cat_travel: "السفر",
    cat_news: "الأخبار",
    cat_movies: "الأفلام",
    diff_beginner: "مبتدئ",
    diff_intermediate: "متوسط",
    diff_advanced: "متقدم",
    // Weakness Tracking Translations (V2 Task 9)
    weaknessesTitle: "نقاط الضعف الصوتية",
    weaknessesDesc: "الكلمات الأكثر صعوبة لديك عبر جميع الجلسات:",
    timesMispronounced: "{count} مرات",
    // V2 Source Mode Translations (Task 4)
    selectSourceMode: "مصدر جمل التدريب",
    modeStatic: "البنك القياسي",
    modeAI: "التوليد الذكي المخصص",
    generatingAI: "جاري توليد الجمل المخصصة بالذكاء الاصطناعي...",
    // V2 Paragraph & Achievement Translations
    selectSessionMode: "اختر نمط التدريب",
    modeSentence: "نمط الجمل",
    modeParagraph: "نمط الفقرات",
    sessionModeSentenceDesc: "تدرب بجمل قصيرة ومنفردة (10 جولات)",
    sessionModeParagraphDesc: "تدرب بفقرات مكونة من عدة جمل (5 جولات)",
    practiceMode: "نمط التدريب",
    achievementsTitle: "الإنجازات المفتوحة",
    achievementsDesc: "الأهداف التي حققتها أثناء تدريبك:",
    downloadCard: "تحميل بطاقة المشاركة",
    generatingShareCard: "جاري توليد بطاقة المشاركة...",
    achievementsUnlockedNotify: "تم فتح إنجاز جديد!"
  }
};
