export type Lang = 'en' | 'ar';

export const translations = {
  en: {
    welcome: "Welcome Back",
    ready: "Ready to shadow your way to fluency?",
    streak: "Current Practice Streak",
    longest: "Longest Streak",
    day: "Day",
    days: "Days",
    totalShadowings: "Total Shadowings",
    avgScore: "Avg Accuracy Score",
    weeklyProgress: "Weekly Progress",
    attemptsPerDay: "Attempts / Day",
    focusTip: "Focus Tip for Today",
    tipBody: "Listen closely to vowel coloring in General American English. Pay attention to rhoticity (the American \"r\") in words like \"water\" or \"there.\" Practice mimicking the exact pitch contour of the prompt!",
    startPractice: "Start Daily Practice",
    progress: "Progress",
    sentenceOf: "Sentence {x} of {y}",
    playingPrompt: "Playing prompt accent...",
    listen: "Listen",
    record: "Record",
    stop: "Stop",
    analyzing: "Analyzing speech acoustics...",
    feedbackPraise: "Praise",
    feedbackCorrection: "Corrective Advice",
    accuracyScore: "Acoustic Score",
    accentAlignment: "General American accent alignment",
    nextSentence: "Next Sentence",
    finishSession: "Finish Session",
    sessionComplete: "Session Complete!",
    sessionDesc: "You just mastered another shadowing round.",
    avgScoreLabel: "Avg Score",
    time: "Time",
    sessionLog: "Session Log",
    home: "Home",
    restart: "Restart",
    voiceSpeed: "Voice Speed",
    tipTitle: "Focus Tip for Today",
    nativeGrade: "Native-grade fluency",
    nativeGradeDesc: "Incredible job! Your articulation and rhythm closely mimic native General American English parameters.",
    clearArtic: "Clear articulation",
    clearArticDesc: "Great work! You have clean phrasing. Keep polishing minor vowel coloring and consonant clarity.",
    keepPractice: "Keep practicing rhythm mechanics",
    keepPracticeDesc: "Keep at it! Pay attention to rhoticity (the American \"r\") and smooth syllable pacing to improve.",
    errorTitle: "Evaluation Error",
    preparing: "Preparing practice block...",
    analyzingAcoustics: "Analyzing speech acoustics...",
    micDenied: "Microphone access denied. Please verify browser permissions.",
    praiseLabel: "Praise",
    correctionLabel: "Correction",
    goBack: "Go back",
    shadowingPractice: "Shadowing Practice",
    acousticScore: "Acoustic Score",
    accentAlignDetail: "General American accent alignment"
  },
  ar: {
    welcome: "مرحباً بك مجدداً",
    ready: "هل أنت مستعد للممارسة والوصول إلى الطلاقة؟",
    streak: "سلسلة الممارسة الحالية",
    longest: "أطول سلسلة ممارسة",
    day: "يوم",
    days: "أيام",
    totalShadowings: "إجمالي المحاولات",
    avgScore: "متوسط نسبة الدقة",
    weeklyProgress: "التقدم الأسبوعي",
    attemptsPerDay: "المحاولات / اليوم",
    focusTip: "نصيحة اليوم للتركيز",
    tipBody: "استمع جيداً لنطق الحروف المتحركة في اللهجة الأمريكية العامة. انتبه لنطق حرف الـ \"r\" في كلمات مثل \"water\" أو \"there\". تدرب على محاكاة نبرة الصوت الدقيقة للجملة!",
    startPractice: "ابدأ الممارسة اليومية",
    progress: "التقدم",
    sentenceOf: "الجملة {x} من {y}",
    playingPrompt: "جاري تشغيل نطق الجملة...",
    listen: "استمع",
    record: "سجل",
    stop: "إيقاف",
    analyzing: "جاري تحليل نبرة الصوت...",
    feedbackPraise: "الإشادة",
    feedbackCorrection: "نصيحة للتصحيح",
    accuracyScore: "درجة النطق",
    accentAlignment: "التوافق مع اللهجة الأمريكية العامة",
    nextSentence: "الجملة التالية",
    finishSession: "إنهاء الجلسة",
    sessionComplete: "اكتملت الجلسة!",
    sessionDesc: "لقد أتقنت جولة أخرى من التدريب.",
    avgScoreLabel: "متوسط الدرجة",
    time: "الوقت",
    sessionLog: "سجل الجلسة",
    home: "الرئيسية",
    restart: "إعادة البدء",
    voiceSpeed: "سرعة الصوت",
    tipTitle: "نصيحة اليوم للتركيز",
    nativeGrade: "طلاقة بمستوى المتحدث الأصلي",
    nativeGradeDesc: "عمل رائع! نطقك ومخارج الحروف لديك قريبة جداً من اللهجة الأمريكية العامة.",
    clearArtic: "نطق واضح ومفهوم",
    clearArticDesc: "عمل جيد! نطقك واضح. استمر في التدرب لتحسين نطق الحروف المتحركة البسيطة ومخارج الحروف.",
    keepPractice: "استمر في التدرب على الإيقاع",
    keepPracticeDesc: "واصل التدريب! ركز على نطق حرف الـ \"r\" الأمريكي وتدفق الجملة بشكل أكثر سلاسة.",
    errorTitle: "خطأ في التقييم",
    preparing: "جاري تجهيز جمل الممارسة...",
    analyzingAcoustics: "جاري تحليل الخصائص الصوتية للخطاب...",
    micDenied: "تم رفض الوصول للميكروفون. يرجى تفعيل الصلاحيات من إعدادات المتصفح.",
    praiseLabel: "الإشادة",
    correctionLabel: "التصحيح",
    goBack: "رجوع",
    shadowingPractice: "التدريب على المحاكاة",
    acousticScore: "درجة النطق",
    accentAlignDetail: "التوافق مع اللهجة الأمريكية العامة"
  }
};
